In [1]:
import pandas as pd
import re

In [4]:
df = pd.read_csv("final-data.csv")

C:\Users\vidhi\AppData\Local\Temp\ipykernel_14632\3608749022.py:1: DtypeWarning: Columns (13,15,17,18,19,20,21,22,23,24,26,28,49,50,51,52,53,54,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("final-data.csv")

In [5]:
df.head()

,date,district,city,facilityid,doctorname,medongoid,appointmenttime,gender,age,diagnosis,...,duration_11,drug_12,dosage_12,duration_12,drug_13,dosage_13,duration_13,drug_14,dosage_14,duration_14
0,2017-06-10,West,Uttam Nagar,320721,NISHANT,1.162021e+09,13:07:17,0,30.0,['body pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-04-26,West,Vikas Puri,310710,Dr. Ravikant,1.116585e+09,12:26:25,1,31.0,['acute respiratory tract infection'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-04,West,Vikas Puri,310710,Dr. Ravikant,1.367039e+09,10:06:51,1,28.0,['influenza'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-12-03,West,Vikas Puri,310724,Shailender,1.120420e+09,08:47:58,1,35.0,"['dermatitis+eczema', 'gastroenteritis']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-06-29,West,Uttam Nagar,320712,Dr. R.C.Khanna,1.367939e+09,11:41:40,1,42.0,['back pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
search_term = 'A'
mask = df.applymap(lambda x: isinstance(x, str) and search_term in x)

filtered_df = df[mask.any(axis=1)]
filtered_df.head(100)

C:\Users\vidhi\AppData\Local\Temp\ipykernel_14632\2941012965.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = df.applymap(lambda x: isinstance(x, str) and search_term in x)

,date,district,city,facilityid,doctorname,medongoid,appointmenttime,gender,age,diagnosis,...,duration_11,drug_12,dosage_12,duration_12,drug_13,dosage_13,duration_13,drug_14,dosage_14,duration_14
0,2017-06-10,West,Uttam Nagar,320721,NISHANT,1.162021e+09,13:07:17,0,30.0,['body pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-04-26,West,Vikas Puri,310710,Dr. Ravikant,1.116585e+09,12:26:25,1,31.0,['acute respiratory tract infection'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-06-29,West,Uttam Nagar,320712,Dr. R.C.Khanna,1.367939e+09,11:41:40,1,42.0,['back pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2019-06-29,West,Uttam Nagar,320712,Dr. R.C.Khanna,1.367939e+09,11:18:14,0,52.0,['acute nasopharyngitis'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2017-09-08,West,Madipur,360718,Dr. Narendra,1.245336e+09,11:56:51,0,33.0,['back pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2019-06-29,West,Vikas Puri,310708,S.K. Arora,1.367937e+09,13:39:11,1,50.0,['type 2 diabetes mellitus'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,2019-06-29,West,Vikas Puri,310708,S.K. Arora,1.367937e+09,13:38:11,0,5.0,['taeniasis'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,2017-04-13,West,Madipur,360718,Dr. Narendra,1.082460e+09,10:57:57,1,21.0,['back pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,2017-08-17,West,Uttam Nagar,320712,Dr. R.C.Khanna,1.102307e+09,12:03:32,1,22.0,['gastroenteritis'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,2019-06-29,West,Vikas Puri,310708,S.K. Arora,1.367937e+09,13:32:24,0,25.0,['headache'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
filtered_df.to_csv("sample-data.csv")

In [25]:
values_to_replace = ['Acetyl Salicylic Acid 7','Acetyl Salicylic Acid 75','Acetyl Salicylic Acid 75 t','Acetyl Salicylic Acid 75 ta','Acetyl Salicylic Acid 75 tab']

df.replace(values_to_replace, 'Acetyl Salicylic Acid 75 tab', inplace=True)

df.to_csv('final-data.csv', index=False)
df.head()

,date,district,city,facilityid,doctorname,medongoid,appointmenttime,gender,age,diagnosis,...,duration_11,drug_12,dosage_12,duration_12,drug_13,dosage_13,duration_13,drug_14,dosage_14,duration_14
0,2017-06-10,West,Uttam Nagar,320721,NISHANT,1.162021e+09,13:07:17,0,30.0,['body pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-04-26,West,Vikas Puri,310710,Dr. Ravikant,1.116585e+09,12:26:25,1,31.0,['acute respiratory tract infection'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-04,West,Vikas Puri,310710,Dr. Ravikant,1.367039e+09,10:06:51,1,28.0,['influenza'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-12-03,West,Vikas Puri,310724,Shailender,1.120420e+09,08:47:58,1,35.0,"['dermatitis+eczema', 'gastroenteritis']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-06-29,West,Uttam Nagar,320712,Dr. R.C.Khanna,1.367939e+09,11:41:40,1,42.0,['back pain'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
search_term = 'Acetyl Salicylic Acid 75 tab'
mask = df.applymap(lambda x: isinstance(x, str) and search_term in x)

filtered_df = df[mask.any(axis=1)]
filtered_df.head(100)
filtered_df.to_csv('sample-data.csv', index=False)

C:\Users\vidhi\AppData\Local\Temp\ipykernel_14632\2468918740.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = df.applymap(lambda x: isinstance(x, str) and search_term in x)

In [16]:
data = pd.read_csv("updated_data.csv")

C:\Users\vidhi\AppData\Local\Temp\ipykernel_14632\2451893032.py:1: DtypeWarning: Columns (13,15,17,18,19,20,21,22,23,24,26,28,49,50,51,52,53,54,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("updated_data.csv")

In [21]:
search_term = '##Acet'
mask = data.applymap(lambda x: isinstance(x, str) and search_term in x)

filtered_df = data[mask.any(axis=1)]
filtered_df.head(100)

C:\Users\vidhi\AppData\Local\Temp\ipykernel_14632\123499936.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = data.applymap(lambda x: isinstance(x, str) and search_term in x)

Empty DataFrame
Columns: [date, district, city, facilityid, doctorname, medongoid, appointmenttime, gender, age, diagnosis, Symptom1, Duration1, Symptom2, Duration2, Symptom3, Duration3, Symptom4, Duration4, Symptom5, Duration5, Symptom6, Duration6, Symptom7, Duration7, Symptom8, Duration8, Symptom9, Duration9, Symptom10, Duration10, drug_1, dosage_1, duration_1, drug_2, dosage_2, duration_2, drug_3, dosage_3, duration_3, drug_4, dosage_4, duration_4, drug_5, dosage_5, duration_5, drug_6, dosage_6, duration_6, drug_7, dosage_7, duration_7, drug_8, dosage_8, duration_8, drug_9, dosage_9, duration_9, drug_10, dosage_10, duration_10, drug_11, dosage_11, duration_11, drug_12, dosage_12, duration_12, drug_13, dosage_13, duration_13, drug_14, dosage_14, duration_14]
Index: []

[0 rows x 72 columns]